// Code generated by "stringer -type=StorageType -trimprefix=StorageType"; DO NOT EDIT.

package db

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[storageTypeUnknown-0]
	_ = x[StorageTypeMongo-1]
	_ = x[storageTypeSentinel-2]
}

const _StorageType_name = "storageTypeUnknownMongostorageTypeSentinel"

var _StorageType_index = [...]uint8{0, 18, 23, 42}

func (i StorageType) String() string {
	if i >= StorageType(len(_StorageType_index)-1) {
		return "StorageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StorageType_name[_StorageType_index[i]:_StorageType_index[i+1]]
}
